/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as TronergyApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const CreateOrder: core.serialization.Schema<serializers.CreateOrder.Raw, TronergyApi.CreateOrder> =
    core.serialization.object({
        address: core.serialization.string(),
        energy: core.serialization.number(),
        period: core.serialization.stringLiteral("1H").optional(),
        callback: core.serialization.string().optional(),
    });

export declare namespace CreateOrder {
    export interface Raw {
        address: string;
        energy: number;
        period?: "1H" | null;
        callback?: string | null;
    }
}
