/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as TronergyApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const CreateOrderDto: core.serialization.Schema<serializers.CreateOrderDto.Raw, TronergyApi.CreateOrderDto> =
    core.serialization.object({
        address: core.serialization.string(),
        energy: core.serialization.number(),
        period: core.serialization.string(),
        callback: core.serialization.string().optional(),
    });

export declare namespace CreateOrderDto {
    export interface Raw {
        address: string;
        energy: number;
        period: string;
        callback?: string | null;
    }
}
