/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Current status of the order.
 */
export type OrderStatus = "PENDING" | "SUCCESS" | "FAILED";
export const OrderStatus = {
    Pending: "PENDING",
    Success: "SUCCESS",
    Failed: "FAILED",
} as const;
