/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TronergyApi from "../index";

export interface OrderDto {
    /** Details of the order. */
    order: TronergyApi.Order;
}
