/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         address: "TXY1kVZ74wLg4mPRPoK9o1RG99NY82MHEV",
 *         energy: 66000
 *     }
 */
export interface CreateOrder {
    /** The Tron wallet address of the user placing the order. Must be a valid Tron address. */
    address: string;
    /** The amount of energy the user wants to purchase, expressed in energy units. */
    energy: number;
    /** The time period for which the energy will be valid. Acceptable values are defined in the EnergyPeriod enum. */
    period?: "1H";
    /** Optional callback URL where a notification will be sent upon order completion. This URL should be accessible by the API service. */
    callback?: string;
}
