/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TronergyApi from "../../api/index";
import * as core from "../../core";
import { Order } from "./Order";

export const OrdersDto: core.serialization.ObjectSchema<serializers.OrdersDto.Raw, TronergyApi.OrdersDto> =
    core.serialization.object({
        orders: core.serialization.list(Order),
    });

export declare namespace OrdersDto {
    export interface Raw {
        orders: Order.Raw[];
    }
}
