/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TronergyApi from "../../api/index";
import * as core from "../../core";

export const OrderStatus: core.serialization.Schema<serializers.OrderStatus.Raw, TronergyApi.OrderStatus> =
    core.serialization.enum_(["PENDING", "SUCCESS", "FAILED"]);

export declare namespace OrderStatus {
    export type Raw = "PENDING" | "SUCCESS" | "FAILED";
}
