/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TronergyApi from "../../api/index";
import * as core from "../../core";
import { Order } from "./Order";

export const OrderDto: core.serialization.ObjectSchema<serializers.OrderDto.Raw, TronergyApi.OrderDto> =
    core.serialization.object({
        order: Order,
    });

export declare namespace OrderDto {
    export interface Raw {
        order: Order.Raw;
    }
}
