/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TronergyApi from "../../api/index";
import * as core from "../../core";

export const RateDto: core.serialization.ObjectSchema<serializers.RateDto.Raw, TronergyApi.RateDto> =
    core.serialization.object({
        rate: core.serialization.number(),
    });

export declare namespace RateDto {
    export interface Raw {
        rate: number;
    }
}
