/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const TronergyApiEnvironment = {
    Production: "https://api-gateway-production-c20d.up.railway.app",
} as const;

export type TronergyApiEnvironment = typeof TronergyApiEnvironment.Production;
