/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const TronergyApiEnvironment = {
    Production: "https://api.tronergy.io/api",
} as const;

export type TronergyApiEnvironment = typeof TronergyApiEnvironment.Production;
